# samson runs as a single server process, so we don't need redis
# TODO: investigate if async adapter has advantages
development:
  adapter: inline

test:
  adapter: inline

staging:
  adapter: inline

production:
  adapter: inline
