#!/bin/sh

set -e

bundle install --local

if [ ! -f .env ]; then
  cp .env.example .env
  echo '[\033[32mNOTE\033[0m] To use GitHub, you have to configure \033[32msamson/.env\033[0m'
else
  echo '.env file exists, not overwriting.'
fi

if [ ! -f config/database.yml ]; then
  cp config/database.mysql.yml.example config/database.yml || true
else
  echo 'config/database.yml file exists, not overwriting.'
fi

bundle exec rake db:setup
