#!/bin/sh

set -e

bundle install --local

cp .env.example .env

ln -vs database.mysql.yml.example config/database.yml || true
ln -vs redis.yml.example config/redis.yml || true
ln -vs redis.development.conf.example config/redis.development.conf || true

bundle exec rake db:setup
