#!/bin/bash

set -e

case $TASK in
js)
  npm install
  npm run-script jshint
  npm run-script jshint:plugins
  DATABASE_URL=mysql2://none@none/none bundle exec rake test:js
  ;;
precompile)
  export SECRET_TOKEN=foo
  export GITHUB_TOKEN=foo
  export PRECOMPILE=1
  export DATABASE_URL=mysql2://none@none/none
  bundle exec rake assets:precompile
  ;;
rake)
  bundle exec rake db:create default
  ;;
*)
  echo "Unknown task"
  ;;
esac
