#!/bin/bash -ex

bundle install --local --quiet --jobs 4 || bundle check

if [ ! -f .env ]; then
    cp .env.bootstrap .env
    # to use .env.virtualbox with 192.168.42.45 host prefix ./bin/decode_dot_env .env.virtualbox && source <(sed -E -n 's/[^#]+/export &/ p' .env.virtualbox) &&
    ./bin/decode_dot_env .env
fi

if [ -f db/development.sqlite3 ]; then
    bundle exec rake db:migrate 
else
    bundle exec rake db:setup || bundle exec rake db:migrate
fi

exec bundle exec puma -C config/puma.rb
